print("====================================")
print("      AI STUDY ASSISTANT")
print("====================================")

name = input("Enter your name: ")
age = int(input("Enter your age: "))
college = input("Enter your college: ")
course = input("Enter your course: ")
semester = input("Enter your semester: ")
goal = input("What is your goal? ")

print("\n========== STUDENT PROFILE ==========")
print("Name      :", name)
print("Age       :", age)
print("College   :", college)
print("Course    :", course)
print("Semester  :", semester)
print("Goal      :", goal)
print("====================================")